trigger:
- main 
variables:
  WORK_DIR: '$(System.DefaultWorkingDirectory)/todoapp_infra'
pool: 'zelectric_pool'

stages:
  - template: templates/tf-template.yml
    parameters:
      environment: dev